-- Create table for tracking read chapters
CREATE TABLE IF NOT EXISTS public.user_reads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) NOT NULL,
    obra_id INTEGER NOT NULL,
    obra_nome TEXT,
    obr_slug TEXT,
    obr_imagem TEXT,
    capitulo_id INTEGER NOT NULL,
    capitulo_numero FLOAT,
    cap_nome TEXT,
    lido_em TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, capitulo_id)
);

-- Enable RLS
ALTER TABLE public.user_reads ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Users can insert their own reads" ON public.user_reads
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own reads" ON public.user_reads
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can view their own reads" ON public.user_reads
    FOR SELECT USING (auth.uid() = user_id);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_user_reads_user_id ON public.user_reads(user_id);
CREATE INDEX IF NOT EXISTS idx_user_reads_obra_id ON public.user_reads(obra_id);
